[tool.poetry]
name = "sir-robin"
version = "0.1.0"
description = ""
authors = ["Python Discord <info@pythondiscord.com>"]

[tool.poetry.dependencies]
python = "3.11.*"

pydis-core = { version = "10.4.0", extras = ["async-rediscache"]}
arrow = "1.3.0"
pydantic-settings = "2.1.0"

[tool.poetry.group.dev.dependencies]
taskipy = "1.12.2"

[tool.poetry.group.test.dependencies]
pytest = "7.4.3"
pytest-asyncio = "0.21.1"
hypothesis = "6.90.0"

[tool.poetry.group.lint.dependencies]
ruff = "0.1.6"
pre-commit = "3.5.0"

[tool.taskipy.tasks]
start = "python -m bot"
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
test = "python -m unittest discover"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"
extend-exclude = [".cache"]
ignore = [
    "ANN002", "ANN003", "ANN101", "ANN102", "ANN204", "ANN206", "ANN401",
    "B904",
    "C401", "C408",
    "D100", "D104", "D105", "D107", "D203", "D212", "D214", "D215", "D301",
    "D400", "D401", "D402", "D404", "D405", "D406", "D407", "D408", "D409", "D410", "D411", "D412", "D413", "D414", "D416", "D417",
    "E731",
    "RET504",
    "RUF005", "RUF012", "RUF015",
    "S311",
    "SIM102", "SIM108",
]
line-length = 120
select = ["ANN", "B", "C4", "D", "DTZ", "E", "F", "I", "ISC", "INT", "N", "PGH", "PIE", "Q", "RET", "RSE", "RUF", "S", "SIM", "T20", "TID", "UP", "W"]
unsafe-fixes = true
preview = true

[tool.ruff.isort]
order-by-type = false
case-sensitive = true
combine-as-imports = true

[tool.ruff.per-file-ignores]
"tests/*" = ["ANN", "D"]
